#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackendProyectoFinal.DataAccess
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="proyectoprogra5")]
	public partial class LinqConexionDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertTB_Amistad(TB_Amistad instance);
    partial void UpdateTB_Amistad(TB_Amistad instance);
    partial void DeleteTB_Amistad(TB_Amistad instance);
    partial void InsertTB_Movimiento(TB_Movimiento instance);
    partial void UpdateTB_Movimiento(TB_Movimiento instance);
    partial void DeleteTB_Movimiento(TB_Movimiento instance);
    partial void InsertTB_PartidaFutbolito(TB_PartidaFutbolito instance);
    partial void UpdateTB_PartidaFutbolito(TB_PartidaFutbolito instance);
    partial void DeleteTB_PartidaFutbolito(TB_PartidaFutbolito instance);
    partial void InsertTB_PartidaGalaga(TB_PartidaGalaga instance);
    partial void UpdateTB_PartidaGalaga(TB_PartidaGalaga instance);
    partial void DeleteTB_PartidaGalaga(TB_PartidaGalaga instance);
    partial void InsertTB_Turno(TB_Turno instance);
    partial void UpdateTB_Turno(TB_Turno instance);
    partial void DeleteTB_Turno(TB_Turno instance);
    partial void InsertTB_Usuario(TB_Usuario instance);
    partial void UpdateTB_Usuario(TB_Usuario instance);
    partial void DeleteTB_Usuario(TB_Usuario instance);
    #endregion
		
		public LinqConexionDataContext() : 
				base(global::BackendProyectoFinal.Properties.Settings.Default.proyectoprogra5ConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public LinqConexionDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqConexionDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqConexionDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqConexionDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TB_Amistad> TB_Amistad
		{
			get
			{
				return this.GetTable<TB_Amistad>();
			}
		}
		
		public System.Data.Linq.Table<TB_Movimiento> TB_Movimiento
		{
			get
			{
				return this.GetTable<TB_Movimiento>();
			}
		}
		
		public System.Data.Linq.Table<TB_PartidaFutbolito> TB_PartidaFutbolito
		{
			get
			{
				return this.GetTable<TB_PartidaFutbolito>();
			}
		}
		
		public System.Data.Linq.Table<TB_PartidaGalaga> TB_PartidaGalaga
		{
			get
			{
				return this.GetTable<TB_PartidaGalaga>();
			}
		}
		
		public System.Data.Linq.Table<TB_Turno> TB_Turno
		{
			get
			{
				return this.GetTable<TB_Turno>();
			}
		}
		
		public System.Data.Linq.Table<TB_Usuario> TB_Usuario
		{
			get
			{
				return this.GetTable<TB_Usuario>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_FutbolitoCrearPartida")]
		public int SP_FutbolitoCrearPartida([global::System.Data.Linq.Mapping.ParameterAttribute(Name="V_identificadorUsuario1", DbType="BigInt")] System.Nullable<long> v_identificadorUsuario1, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="V_IdentificadorJuego", DbType="BigInt")] ref System.Nullable<long> v_IdentificadorJuego, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="V_DescripcionError", DbType="NVarChar(255)")] ref string v_DescripcionError)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), v_identificadorUsuario1, v_IdentificadorJuego, v_DescripcionError);
			v_IdentificadorJuego = ((System.Nullable<long>)(result.GetParameterValue(1)));
			v_DescripcionError = ((string)(result.GetParameterValue(2)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_FutbolitoGanador")]
		public int SP_FutbolitoGanador([global::System.Data.Linq.Mapping.ParameterAttribute(Name="V_IdentificadorPartida", DbType="BigInt")] System.Nullable<long> v_IdentificadorPartida, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="V_IdentificadorUsuario", DbType="BigInt")] System.Nullable<long> v_IdentificadorUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="V_DescripcionError", DbType="VarChar(255)")] ref string v_DescripcionError)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), v_IdentificadorPartida, v_IdentificadorUsuario, v_DescripcionError);
			v_DescripcionError = ((string)(result.GetParameterValue(2)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_FutbolitoTurnoResultado")]
		public int SP_FutbolitoTurnoResultado([global::System.Data.Linq.Mapping.ParameterAttribute(Name="V_IdentificadorPartida", DbType="BigInt")] System.Nullable<long> v_IdentificadorPartida, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="V_IdentificadorTurno", DbType="Int")] System.Nullable<int> v_IdentificadorTurno, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="V_NumeroTurno", DbType="Int")] System.Nullable<int> v_NumeroTurno, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="V_IdentificadorTurnoSiguiente", DbType="Int")] ref System.Nullable<int> v_IdentificadorTurnoSiguiente, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="V_DescripcionError", DbType="VarChar(255)")] ref string v_DescripcionError)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), v_IdentificadorPartida, v_IdentificadorTurno, v_NumeroTurno, v_IdentificadorTurnoSiguiente, v_DescripcionError);
			v_IdentificadorTurnoSiguiente = ((System.Nullable<int>)(result.GetParameterValue(3)));
			v_DescripcionError = ((string)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_GalagaCrearPartida")]
		public int SP_GalagaCrearPartida([global::System.Data.Linq.Mapping.ParameterAttribute(Name="V_IdentificadorUsuario", DbType="BigInt")] System.Nullable<long> v_IdentificadorUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="V_PuntajeUsuario", DbType="Int")] System.Nullable<int> v_PuntajeUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="V_Duracion", DbType="Float")] System.Nullable<double> v_Duracion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="V_IdentificadorJuego", DbType="BigInt")] ref System.Nullable<long> v_IdentificadorJuego, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="V_DescripcionError", DbType="NVarChar(255)")] ref string v_DescripcionError)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), v_IdentificadorUsuario, v_PuntajeUsuario, v_Duracion, v_IdentificadorJuego, v_DescripcionError);
			v_IdentificadorJuego = ((System.Nullable<long>)(result.GetParameterValue(3)));
			v_DescripcionError = ((string)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_GalagaObtenerPuntuacionesUsuarios")]
		public ISingleResult<SP_GalagaObtenerPuntuacionesUsuariosResult> SP_GalagaObtenerPuntuacionesUsuarios()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_GalagaObtenerPuntuacionesUsuariosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_UsuarioAmistadIniciar")]
		public int SP_UsuarioAmistadIniciar([global::System.Data.Linq.Mapping.ParameterAttribute(Name="V_identificadorUsuario1", DbType="BigInt")] System.Nullable<long> v_identificadorUsuario1, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="V_identificadorUsuario2", DbType="BigInt")] System.Nullable<long> v_identificadorUsuario2, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="V_Identificador", DbType="Int")] ref System.Nullable<int> v_Identificador, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="V_DescripcionError", DbType="NVarChar(255)")] ref string v_DescripcionError)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), v_identificadorUsuario1, v_identificadorUsuario2, v_Identificador, v_DescripcionError);
			v_Identificador = ((System.Nullable<int>)(result.GetParameterValue(2)));
			v_DescripcionError = ((string)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_UsuarioVerificar")]
		public ISingleResult<SP_UsuarioVerificarResult> SP_UsuarioVerificar([global::System.Data.Linq.Mapping.ParameterAttribute(Name="V_correo", DbType="VarChar(255)")] string v_correo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="V_contrasena", DbType="VarChar(255)")] string v_contrasena, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="V_DescripcionError", DbType="NVarChar(255)")] ref string v_DescripcionError)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), v_correo, v_contrasena, v_DescripcionError);
			v_DescripcionError = ((string)(result.GetParameterValue(2)));
			return ((ISingleResult<SP_UsuarioVerificarResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_UsuarioCrear")]
		public int SP_UsuarioCrear([global::System.Data.Linq.Mapping.ParameterAttribute(Name="V_Nombre", DbType="NVarChar(255)")] string v_Nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="V_FechaNacimiento", DbType="DateTime")] System.Nullable<System.DateTime> v_FechaNacimiento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="V_Contrasena", DbType="NVarChar(255)")] string v_Contrasena, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="V_FotoPerfil", DbType="VarBinary(MAX)")] System.Data.Linq.Binary v_FotoPerfil, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="V_Correo", DbType="NVarChar(255)")] string v_Correo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="V_Indentificador", DbType="BigInt")] ref System.Nullable<long> v_Indentificador, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="V_DescripcionError", DbType="NVarChar(255)")] ref string v_DescripcionError)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), v_Nombre, v_FechaNacimiento, v_Contrasena, v_FotoPerfil, v_Correo, v_Indentificador, v_DescripcionError);
			v_Indentificador = ((System.Nullable<long>)(result.GetParameterValue(5)));
			v_DescripcionError = ((string)(result.GetParameterValue(6)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_UsuarioAmistadEliminar")]
		public int SP_UsuarioAmistadEliminar([global::System.Data.Linq.Mapping.ParameterAttribute(Name="V_identificacionUsuario1", DbType="BigInt")] System.Nullable<long> v_identificacionUsuario1, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="V_identificacionUsuario2", DbType="BigInt")] System.Nullable<long> v_identificacionUsuario2, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="V_Estatus", DbType="Int")] ref System.Nullable<int> v_Estatus, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="V_DescripcionError", DbType="NVarChar(255)")] ref string v_DescripcionError)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), v_identificacionUsuario1, v_identificacionUsuario2, v_Estatus, v_DescripcionError);
			v_Estatus = ((System.Nullable<int>)(result.GetParameterValue(2)));
			v_DescripcionError = ((string)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_UsuarioAmistadListar")]
		public ISingleResult<SP_UsuarioAmistadListarResult> SP_UsuarioAmistadListar([global::System.Data.Linq.Mapping.ParameterAttribute(Name="V_identificacionUsuario", DbType="BigInt")] System.Nullable<long> v_identificacionUsuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), v_identificacionUsuario);
			return ((ISingleResult<SP_UsuarioAmistadListarResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_GalagaPuntuacionUsuario")]
		public ISingleResult<SP_GalagaPuntuacionUsuarioResult> SP_GalagaPuntuacionUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="V_Usuario", DbType="BigInt")] System.Nullable<long> v_Usuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), v_Usuario);
			return ((ISingleResult<SP_GalagaPuntuacionUsuarioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_FutbolitoBuscarPartida")]
		public ISingleResult<SP_FutbolitoBuscarPartidaResult> SP_FutbolitoBuscarPartida([global::System.Data.Linq.Mapping.ParameterAttribute(Name="V_IdentificadorUsuario", DbType="BigInt")] System.Nullable<long> v_IdentificadorUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="V_IdentificadorJeugo", DbType="BigInt")] ref System.Nullable<long> v_IdentificadorJeugo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> v_IdentificadorTurno, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="V_DescripcionError", DbType="NVarChar(255)")] ref string v_DescripcionError, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="V_IdentificadorUsuario1", DbType="BigInt")] ref System.Nullable<long> v_IdentificadorUsuario1, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="V_nombreUsuario1", DbType="NVarChar(255)")] ref string v_nombreUsuario1)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), v_IdentificadorUsuario, v_IdentificadorJeugo, v_IdentificadorTurno, v_DescripcionError, v_IdentificadorUsuario1, v_nombreUsuario1);
			v_IdentificadorJeugo = ((System.Nullable<long>)(result.GetParameterValue(1)));
			v_IdentificadorTurno = ((System.Nullable<int>)(result.GetParameterValue(2)));
			v_DescripcionError = ((string)(result.GetParameterValue(3)));
			v_IdentificadorUsuario1 = ((System.Nullable<long>)(result.GetParameterValue(4)));
			v_nombreUsuario1 = ((string)(result.GetParameterValue(5)));
			return ((ISingleResult<SP_FutbolitoBuscarPartidaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_FutbolitoTraerDatosPartida")]
		public ISingleResult<SP_FutbolitoTraerDatosPartidaResult> SP_FutbolitoTraerDatosPartida([global::System.Data.Linq.Mapping.ParameterAttribute(Name="V_IdentificadorJuego", DbType="BigInt")] System.Nullable<long> v_IdentificadorJuego, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="V_IdentificadorUsuarioGanador", DbType="BigInt")] ref System.Nullable<long> v_IdentificadorUsuarioGanador, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="V_IdentificadorUsuario2", DbType="BigInt")] ref System.Nullable<long> v_IdentificadorUsuario2, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="V_NombreUsuario2", DbType="NVarChar(255)")] ref string v_NombreUsuario2, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="V_DescripcionError", DbType="NVarChar(255)")] ref string v_DescripcionError)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), v_IdentificadorJuego, v_IdentificadorUsuarioGanador, v_IdentificadorUsuario2, v_NombreUsuario2, v_DescripcionError);
			v_IdentificadorUsuarioGanador = ((System.Nullable<long>)(result.GetParameterValue(1)));
			v_IdentificadorUsuario2 = ((System.Nullable<long>)(result.GetParameterValue(2)));
			v_NombreUsuario2 = ((string)(result.GetParameterValue(3)));
			v_DescripcionError = ((string)(result.GetParameterValue(4)));
			return ((ISingleResult<SP_FutbolitoTraerDatosPartidaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_FutbolitoMovimientoInsertar")]
		public int SP_FutbolitoMovimientoInsertar([global::System.Data.Linq.Mapping.ParameterAttribute(Name="V_IdentificadorTurno", DbType="BigInt")] System.Nullable<long> v_IdentificadorTurno, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="V_IdentificadorUsuario", DbType="BigInt")] System.Nullable<long> v_IdentificadorUsuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="V_DireccionX", DbType="Float")] System.Nullable<double> v_DireccionX, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="V_DireccionY", DbType="Float")] System.Nullable<double> v_DireccionY, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="V_TipoJugador", DbType="Int")] System.Nullable<int> v_TipoJugador, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="V_IdentificadorMovimiento", DbType="Int")] ref System.Nullable<int> v_IdentificadorMovimiento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="V_DescripcionError", DbType="VarChar(255)")] ref string v_DescripcionError)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), v_IdentificadorTurno, v_IdentificadorUsuario, v_DireccionX, v_DireccionY, v_TipoJugador, v_IdentificadorMovimiento, v_DescripcionError);
			v_IdentificadorMovimiento = ((System.Nullable<int>)(result.GetParameterValue(5)));
			v_DescripcionError = ((string)(result.GetParameterValue(6)));
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_Amistad")]
	public partial class TB_Amistad : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _identificadorAmistad;
		
		private long _identificadorUsuario1;
		
		private long _identificadorUsuario2;
		
		private System.DateTime _FechaInicio;
		
		private int _Estatus;
		
		private EntityRef<TB_Usuario> _TB_Usuario;
		
		private EntityRef<TB_Usuario> _TB_Usuario1;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidentificadorAmistadChanging(int value);
    partial void OnidentificadorAmistadChanged();
    partial void OnidentificadorUsuario1Changing(long value);
    partial void OnidentificadorUsuario1Changed();
    partial void OnidentificadorUsuario2Changing(long value);
    partial void OnidentificadorUsuario2Changed();
    partial void OnFechaInicioChanging(System.DateTime value);
    partial void OnFechaInicioChanged();
    partial void OnEstatusChanging(int value);
    partial void OnEstatusChanged();
    #endregion
		
		public TB_Amistad()
		{
			this._TB_Usuario = default(EntityRef<TB_Usuario>);
			this._TB_Usuario1 = default(EntityRef<TB_Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_identificadorAmistad", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int identificadorAmistad
		{
			get
			{
				return this._identificadorAmistad;
			}
			set
			{
				if ((this._identificadorAmistad != value))
				{
					this.OnidentificadorAmistadChanging(value);
					this.SendPropertyChanging();
					this._identificadorAmistad = value;
					this.SendPropertyChanged("identificadorAmistad");
					this.OnidentificadorAmistadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_identificadorUsuario1", DbType="BigInt NOT NULL")]
		public long identificadorUsuario1
		{
			get
			{
				return this._identificadorUsuario1;
			}
			set
			{
				if ((this._identificadorUsuario1 != value))
				{
					if (this._TB_Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidentificadorUsuario1Changing(value);
					this.SendPropertyChanging();
					this._identificadorUsuario1 = value;
					this.SendPropertyChanged("identificadorUsuario1");
					this.OnidentificadorUsuario1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_identificadorUsuario2", DbType="BigInt NOT NULL")]
		public long identificadorUsuario2
		{
			get
			{
				return this._identificadorUsuario2;
			}
			set
			{
				if ((this._identificadorUsuario2 != value))
				{
					if (this._TB_Usuario1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidentificadorUsuario2Changing(value);
					this.SendPropertyChanging();
					this._identificadorUsuario2 = value;
					this.SendPropertyChanged("identificadorUsuario2");
					this.OnidentificadorUsuario2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaInicio", DbType="DateTime NOT NULL")]
		public System.DateTime FechaInicio
		{
			get
			{
				return this._FechaInicio;
			}
			set
			{
				if ((this._FechaInicio != value))
				{
					this.OnFechaInicioChanging(value);
					this.SendPropertyChanging();
					this._FechaInicio = value;
					this.SendPropertyChanged("FechaInicio");
					this.OnFechaInicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus", DbType="Int NOT NULL")]
		public int Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this.OnEstatusChanging(value);
					this.SendPropertyChanging();
					this._Estatus = value;
					this.SendPropertyChanged("Estatus");
					this.OnEstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_Usuario_TB_Amistad", Storage="_TB_Usuario", ThisKey="identificadorUsuario1", OtherKey="identificadorUsuario", IsForeignKey=true)]
		public TB_Usuario TB_Usuario
		{
			get
			{
				return this._TB_Usuario.Entity;
			}
			set
			{
				TB_Usuario previousValue = this._TB_Usuario.Entity;
				if (((previousValue != value) 
							|| (this._TB_Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_Usuario.Entity = null;
						previousValue.TB_Amistad.Remove(this);
					}
					this._TB_Usuario.Entity = value;
					if ((value != null))
					{
						value.TB_Amistad.Add(this);
						this._identificadorUsuario1 = value.identificadorUsuario;
					}
					else
					{
						this._identificadorUsuario1 = default(long);
					}
					this.SendPropertyChanged("TB_Usuario");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_Usuario_TB_Amistad1", Storage="_TB_Usuario1", ThisKey="identificadorUsuario2", OtherKey="identificadorUsuario", IsForeignKey=true)]
		public TB_Usuario TB_Usuario1
		{
			get
			{
				return this._TB_Usuario1.Entity;
			}
			set
			{
				TB_Usuario previousValue = this._TB_Usuario1.Entity;
				if (((previousValue != value) 
							|| (this._TB_Usuario1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_Usuario1.Entity = null;
						previousValue.TB_Amistad1.Remove(this);
					}
					this._TB_Usuario1.Entity = value;
					if ((value != null))
					{
						value.TB_Amistad1.Add(this);
						this._identificadorUsuario2 = value.identificadorUsuario;
					}
					else
					{
						this._identificadorUsuario2 = default(long);
					}
					this.SendPropertyChanged("TB_Usuario1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_Movimiento")]
	public partial class TB_Movimiento : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _identificadorMovimiento;
		
		private System.Nullable<int> _identificadorTurno;
		
		private System.Nullable<long> _identificadorUsuario;
		
		private System.Nullable<double> _direccionX;
		
		private System.Nullable<double> _direccionY;
		
		private int _jugador;
		
		private EntityRef<TB_Turno> _TB_Turno;
		
		private EntityRef<TB_Usuario> _TB_Usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidentificadorMovimientoChanging(int value);
    partial void OnidentificadorMovimientoChanged();
    partial void OnidentificadorTurnoChanging(System.Nullable<int> value);
    partial void OnidentificadorTurnoChanged();
    partial void OnidentificadorUsuarioChanging(System.Nullable<long> value);
    partial void OnidentificadorUsuarioChanged();
    partial void OndireccionXChanging(System.Nullable<double> value);
    partial void OndireccionXChanged();
    partial void OndireccionYChanging(System.Nullable<double> value);
    partial void OndireccionYChanged();
    partial void OnjugadorChanging(int value);
    partial void OnjugadorChanged();
    #endregion
		
		public TB_Movimiento()
		{
			this._TB_Turno = default(EntityRef<TB_Turno>);
			this._TB_Usuario = default(EntityRef<TB_Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_identificadorMovimiento", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int identificadorMovimiento
		{
			get
			{
				return this._identificadorMovimiento;
			}
			set
			{
				if ((this._identificadorMovimiento != value))
				{
					this.OnidentificadorMovimientoChanging(value);
					this.SendPropertyChanging();
					this._identificadorMovimiento = value;
					this.SendPropertyChanged("identificadorMovimiento");
					this.OnidentificadorMovimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_identificadorTurno", DbType="Int")]
		public System.Nullable<int> identificadorTurno
		{
			get
			{
				return this._identificadorTurno;
			}
			set
			{
				if ((this._identificadorTurno != value))
				{
					if (this._TB_Turno.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidentificadorTurnoChanging(value);
					this.SendPropertyChanging();
					this._identificadorTurno = value;
					this.SendPropertyChanged("identificadorTurno");
					this.OnidentificadorTurnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_identificadorUsuario", DbType="BigInt")]
		public System.Nullable<long> identificadorUsuario
		{
			get
			{
				return this._identificadorUsuario;
			}
			set
			{
				if ((this._identificadorUsuario != value))
				{
					if (this._TB_Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidentificadorUsuarioChanging(value);
					this.SendPropertyChanging();
					this._identificadorUsuario = value;
					this.SendPropertyChanged("identificadorUsuario");
					this.OnidentificadorUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccionX", DbType="Float")]
		public System.Nullable<double> direccionX
		{
			get
			{
				return this._direccionX;
			}
			set
			{
				if ((this._direccionX != value))
				{
					this.OndireccionXChanging(value);
					this.SendPropertyChanging();
					this._direccionX = value;
					this.SendPropertyChanged("direccionX");
					this.OndireccionXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccionY", DbType="Float")]
		public System.Nullable<double> direccionY
		{
			get
			{
				return this._direccionY;
			}
			set
			{
				if ((this._direccionY != value))
				{
					this.OndireccionYChanging(value);
					this.SendPropertyChanging();
					this._direccionY = value;
					this.SendPropertyChanged("direccionY");
					this.OndireccionYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jugador", DbType="Int NOT NULL")]
		public int jugador
		{
			get
			{
				return this._jugador;
			}
			set
			{
				if ((this._jugador != value))
				{
					this.OnjugadorChanging(value);
					this.SendPropertyChanging();
					this._jugador = value;
					this.SendPropertyChanged("jugador");
					this.OnjugadorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_Turno_TB_Movimiento", Storage="_TB_Turno", ThisKey="identificadorTurno", OtherKey="identificadorTurno", IsForeignKey=true)]
		public TB_Turno TB_Turno
		{
			get
			{
				return this._TB_Turno.Entity;
			}
			set
			{
				TB_Turno previousValue = this._TB_Turno.Entity;
				if (((previousValue != value) 
							|| (this._TB_Turno.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_Turno.Entity = null;
						previousValue.TB_Movimiento.Remove(this);
					}
					this._TB_Turno.Entity = value;
					if ((value != null))
					{
						value.TB_Movimiento.Add(this);
						this._identificadorTurno = value.identificadorTurno;
					}
					else
					{
						this._identificadorTurno = default(Nullable<int>);
					}
					this.SendPropertyChanged("TB_Turno");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_Usuario_TB_Movimiento", Storage="_TB_Usuario", ThisKey="identificadorUsuario", OtherKey="identificadorUsuario", IsForeignKey=true)]
		public TB_Usuario TB_Usuario
		{
			get
			{
				return this._TB_Usuario.Entity;
			}
			set
			{
				TB_Usuario previousValue = this._TB_Usuario.Entity;
				if (((previousValue != value) 
							|| (this._TB_Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_Usuario.Entity = null;
						previousValue.TB_Movimiento.Remove(this);
					}
					this._TB_Usuario.Entity = value;
					if ((value != null))
					{
						value.TB_Movimiento.Add(this);
						this._identificadorUsuario = value.identificadorUsuario;
					}
					else
					{
						this._identificadorUsuario = default(Nullable<long>);
					}
					this.SendPropertyChanged("TB_Usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_PartidaFutbolito")]
	public partial class TB_PartidaFutbolito : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _identificadorJuego;
		
		private long _identificadorUsuario1;
		
		private System.Nullable<long> _identificadorUsuario2;
		
		private System.Nullable<System.DateTime> _fecha;
		
		private long _usuarioGanadorPartida;
		
		private EntitySet<TB_Turno> _TB_Turno;
		
		private EntityRef<TB_Usuario> _TB_Usuario;
		
		private EntityRef<TB_Usuario> _TB_Usuario1;
		
		private EntityRef<TB_Usuario> _TB_Usuario2;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidentificadorJuegoChanging(long value);
    partial void OnidentificadorJuegoChanged();
    partial void OnidentificadorUsuario1Changing(long value);
    partial void OnidentificadorUsuario1Changed();
    partial void OnidentificadorUsuario2Changing(System.Nullable<long> value);
    partial void OnidentificadorUsuario2Changed();
    partial void OnfechaChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaChanged();
    partial void OnusuarioGanadorPartidaChanging(long value);
    partial void OnusuarioGanadorPartidaChanged();
    #endregion
		
		public TB_PartidaFutbolito()
		{
			this._TB_Turno = new EntitySet<TB_Turno>(new Action<TB_Turno>(this.attach_TB_Turno), new Action<TB_Turno>(this.detach_TB_Turno));
			this._TB_Usuario = default(EntityRef<TB_Usuario>);
			this._TB_Usuario1 = default(EntityRef<TB_Usuario>);
			this._TB_Usuario2 = default(EntityRef<TB_Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_identificadorJuego", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long identificadorJuego
		{
			get
			{
				return this._identificadorJuego;
			}
			set
			{
				if ((this._identificadorJuego != value))
				{
					this.OnidentificadorJuegoChanging(value);
					this.SendPropertyChanging();
					this._identificadorJuego = value;
					this.SendPropertyChanged("identificadorJuego");
					this.OnidentificadorJuegoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_identificadorUsuario1", DbType="BigInt NOT NULL")]
		public long identificadorUsuario1
		{
			get
			{
				return this._identificadorUsuario1;
			}
			set
			{
				if ((this._identificadorUsuario1 != value))
				{
					if (this._TB_Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidentificadorUsuario1Changing(value);
					this.SendPropertyChanging();
					this._identificadorUsuario1 = value;
					this.SendPropertyChanged("identificadorUsuario1");
					this.OnidentificadorUsuario1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_identificadorUsuario2", DbType="BigInt")]
		public System.Nullable<long> identificadorUsuario2
		{
			get
			{
				return this._identificadorUsuario2;
			}
			set
			{
				if ((this._identificadorUsuario2 != value))
				{
					if (this._TB_Usuario1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidentificadorUsuario2Changing(value);
					this.SendPropertyChanging();
					this._identificadorUsuario2 = value;
					this.SendPropertyChanged("identificadorUsuario2");
					this.OnidentificadorUsuario2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this.OnfechaChanging(value);
					this.SendPropertyChanging();
					this._fecha = value;
					this.SendPropertyChanged("fecha");
					this.OnfechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuarioGanadorPartida", DbType="BigInt NOT NULL")]
		public long usuarioGanadorPartida
		{
			get
			{
				return this._usuarioGanadorPartida;
			}
			set
			{
				if ((this._usuarioGanadorPartida != value))
				{
					if (this._TB_Usuario2.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnusuarioGanadorPartidaChanging(value);
					this.SendPropertyChanging();
					this._usuarioGanadorPartida = value;
					this.SendPropertyChanged("usuarioGanadorPartida");
					this.OnusuarioGanadorPartidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_PartidaFutbolito_TB_Turno", Storage="_TB_Turno", ThisKey="identificadorJuego", OtherKey="identificadorPartida")]
		public EntitySet<TB_Turno> TB_Turno
		{
			get
			{
				return this._TB_Turno;
			}
			set
			{
				this._TB_Turno.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_Usuario_TB_PartidaFutbolito", Storage="_TB_Usuario", ThisKey="identificadorUsuario1", OtherKey="identificadorUsuario", IsForeignKey=true)]
		public TB_Usuario TB_Usuario
		{
			get
			{
				return this._TB_Usuario.Entity;
			}
			set
			{
				TB_Usuario previousValue = this._TB_Usuario.Entity;
				if (((previousValue != value) 
							|| (this._TB_Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_Usuario.Entity = null;
						previousValue.TB_PartidaFutbolito.Remove(this);
					}
					this._TB_Usuario.Entity = value;
					if ((value != null))
					{
						value.TB_PartidaFutbolito.Add(this);
						this._identificadorUsuario1 = value.identificadorUsuario;
					}
					else
					{
						this._identificadorUsuario1 = default(long);
					}
					this.SendPropertyChanged("TB_Usuario");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_Usuario_TB_PartidaFutbolito1", Storage="_TB_Usuario1", ThisKey="identificadorUsuario2", OtherKey="identificadorUsuario", IsForeignKey=true)]
		public TB_Usuario TB_Usuario1
		{
			get
			{
				return this._TB_Usuario1.Entity;
			}
			set
			{
				TB_Usuario previousValue = this._TB_Usuario1.Entity;
				if (((previousValue != value) 
							|| (this._TB_Usuario1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_Usuario1.Entity = null;
						previousValue.TB_PartidaFutbolito1.Remove(this);
					}
					this._TB_Usuario1.Entity = value;
					if ((value != null))
					{
						value.TB_PartidaFutbolito1.Add(this);
						this._identificadorUsuario2 = value.identificadorUsuario;
					}
					else
					{
						this._identificadorUsuario2 = default(Nullable<long>);
					}
					this.SendPropertyChanged("TB_Usuario1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_Usuario_TB_PartidaFutbolito2", Storage="_TB_Usuario2", ThisKey="usuarioGanadorPartida", OtherKey="identificadorUsuario", IsForeignKey=true)]
		public TB_Usuario TB_Usuario2
		{
			get
			{
				return this._TB_Usuario2.Entity;
			}
			set
			{
				TB_Usuario previousValue = this._TB_Usuario2.Entity;
				if (((previousValue != value) 
							|| (this._TB_Usuario2.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_Usuario2.Entity = null;
						previousValue.TB_PartidaFutbolito2.Remove(this);
					}
					this._TB_Usuario2.Entity = value;
					if ((value != null))
					{
						value.TB_PartidaFutbolito2.Add(this);
						this._usuarioGanadorPartida = value.identificadorUsuario;
					}
					else
					{
						this._usuarioGanadorPartida = default(long);
					}
					this.SendPropertyChanged("TB_Usuario2");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TB_Turno(TB_Turno entity)
		{
			this.SendPropertyChanging();
			entity.TB_PartidaFutbolito = this;
		}
		
		private void detach_TB_Turno(TB_Turno entity)
		{
			this.SendPropertyChanging();
			entity.TB_PartidaFutbolito = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_PartidaGalaga")]
	public partial class TB_PartidaGalaga : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _identificadorJuego;
		
		private long _identificadorUsuario1;
		
		private int _PuntajeUsuario1;
		
		private double _duracion;
		
		private System.DateTime _fechaJuego;
		
		private EntityRef<TB_Usuario> _TB_Usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidentificadorJuegoChanging(long value);
    partial void OnidentificadorJuegoChanged();
    partial void OnidentificadorUsuario1Changing(long value);
    partial void OnidentificadorUsuario1Changed();
    partial void OnPuntajeUsuario1Changing(int value);
    partial void OnPuntajeUsuario1Changed();
    partial void OnduracionChanging(double value);
    partial void OnduracionChanged();
    partial void OnfechaJuegoChanging(System.DateTime value);
    partial void OnfechaJuegoChanged();
    #endregion
		
		public TB_PartidaGalaga()
		{
			this._TB_Usuario = default(EntityRef<TB_Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_identificadorJuego", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long identificadorJuego
		{
			get
			{
				return this._identificadorJuego;
			}
			set
			{
				if ((this._identificadorJuego != value))
				{
					this.OnidentificadorJuegoChanging(value);
					this.SendPropertyChanging();
					this._identificadorJuego = value;
					this.SendPropertyChanged("identificadorJuego");
					this.OnidentificadorJuegoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_identificadorUsuario1", DbType="BigInt NOT NULL")]
		public long identificadorUsuario1
		{
			get
			{
				return this._identificadorUsuario1;
			}
			set
			{
				if ((this._identificadorUsuario1 != value))
				{
					if (this._TB_Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidentificadorUsuario1Changing(value);
					this.SendPropertyChanging();
					this._identificadorUsuario1 = value;
					this.SendPropertyChanged("identificadorUsuario1");
					this.OnidentificadorUsuario1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PuntajeUsuario1", DbType="Int NOT NULL")]
		public int PuntajeUsuario1
		{
			get
			{
				return this._PuntajeUsuario1;
			}
			set
			{
				if ((this._PuntajeUsuario1 != value))
				{
					this.OnPuntajeUsuario1Changing(value);
					this.SendPropertyChanging();
					this._PuntajeUsuario1 = value;
					this.SendPropertyChanged("PuntajeUsuario1");
					this.OnPuntajeUsuario1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_duracion", DbType="Float NOT NULL")]
		public double duracion
		{
			get
			{
				return this._duracion;
			}
			set
			{
				if ((this._duracion != value))
				{
					this.OnduracionChanging(value);
					this.SendPropertyChanging();
					this._duracion = value;
					this.SendPropertyChanged("duracion");
					this.OnduracionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaJuego", DbType="DateTime NOT NULL")]
		public System.DateTime fechaJuego
		{
			get
			{
				return this._fechaJuego;
			}
			set
			{
				if ((this._fechaJuego != value))
				{
					this.OnfechaJuegoChanging(value);
					this.SendPropertyChanging();
					this._fechaJuego = value;
					this.SendPropertyChanged("fechaJuego");
					this.OnfechaJuegoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_Usuario_TB_PartidaGalaga", Storage="_TB_Usuario", ThisKey="identificadorUsuario1", OtherKey="identificadorUsuario", IsForeignKey=true)]
		public TB_Usuario TB_Usuario
		{
			get
			{
				return this._TB_Usuario.Entity;
			}
			set
			{
				TB_Usuario previousValue = this._TB_Usuario.Entity;
				if (((previousValue != value) 
							|| (this._TB_Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_Usuario.Entity = null;
						previousValue.TB_PartidaGalaga.Remove(this);
					}
					this._TB_Usuario.Entity = value;
					if ((value != null))
					{
						value.TB_PartidaGalaga.Add(this);
						this._identificadorUsuario1 = value.identificadorUsuario;
					}
					else
					{
						this._identificadorUsuario1 = default(long);
					}
					this.SendPropertyChanged("TB_Usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_Turno")]
	public partial class TB_Turno : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _identificadorTurno;
		
		private System.Nullable<long> _identificadorPartida;
		
		private System.Nullable<int> _numeroTurno;
		
		private System.Nullable<long> _usuarioGanador;
		
		private EntitySet<TB_Movimiento> _TB_Movimiento;
		
		private EntityRef<TB_PartidaFutbolito> _TB_PartidaFutbolito;
		
		private EntityRef<TB_Usuario> _TB_Usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidentificadorTurnoChanging(int value);
    partial void OnidentificadorTurnoChanged();
    partial void OnidentificadorPartidaChanging(System.Nullable<long> value);
    partial void OnidentificadorPartidaChanged();
    partial void OnnumeroTurnoChanging(System.Nullable<int> value);
    partial void OnnumeroTurnoChanged();
    partial void OnusuarioGanadorChanging(System.Nullable<long> value);
    partial void OnusuarioGanadorChanged();
    #endregion
		
		public TB_Turno()
		{
			this._TB_Movimiento = new EntitySet<TB_Movimiento>(new Action<TB_Movimiento>(this.attach_TB_Movimiento), new Action<TB_Movimiento>(this.detach_TB_Movimiento));
			this._TB_PartidaFutbolito = default(EntityRef<TB_PartidaFutbolito>);
			this._TB_Usuario = default(EntityRef<TB_Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_identificadorTurno", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int identificadorTurno
		{
			get
			{
				return this._identificadorTurno;
			}
			set
			{
				if ((this._identificadorTurno != value))
				{
					this.OnidentificadorTurnoChanging(value);
					this.SendPropertyChanging();
					this._identificadorTurno = value;
					this.SendPropertyChanged("identificadorTurno");
					this.OnidentificadorTurnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_identificadorPartida", DbType="BigInt")]
		public System.Nullable<long> identificadorPartida
		{
			get
			{
				return this._identificadorPartida;
			}
			set
			{
				if ((this._identificadorPartida != value))
				{
					if (this._TB_PartidaFutbolito.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidentificadorPartidaChanging(value);
					this.SendPropertyChanging();
					this._identificadorPartida = value;
					this.SendPropertyChanged("identificadorPartida");
					this.OnidentificadorPartidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numeroTurno", DbType="Int")]
		public System.Nullable<int> numeroTurno
		{
			get
			{
				return this._numeroTurno;
			}
			set
			{
				if ((this._numeroTurno != value))
				{
					this.OnnumeroTurnoChanging(value);
					this.SendPropertyChanging();
					this._numeroTurno = value;
					this.SendPropertyChanged("numeroTurno");
					this.OnnumeroTurnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuarioGanador", DbType="BigInt")]
		public System.Nullable<long> usuarioGanador
		{
			get
			{
				return this._usuarioGanador;
			}
			set
			{
				if ((this._usuarioGanador != value))
				{
					if (this._TB_Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnusuarioGanadorChanging(value);
					this.SendPropertyChanging();
					this._usuarioGanador = value;
					this.SendPropertyChanged("usuarioGanador");
					this.OnusuarioGanadorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_Turno_TB_Movimiento", Storage="_TB_Movimiento", ThisKey="identificadorTurno", OtherKey="identificadorTurno")]
		public EntitySet<TB_Movimiento> TB_Movimiento
		{
			get
			{
				return this._TB_Movimiento;
			}
			set
			{
				this._TB_Movimiento.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_PartidaFutbolito_TB_Turno", Storage="_TB_PartidaFutbolito", ThisKey="identificadorPartida", OtherKey="identificadorJuego", IsForeignKey=true)]
		public TB_PartidaFutbolito TB_PartidaFutbolito
		{
			get
			{
				return this._TB_PartidaFutbolito.Entity;
			}
			set
			{
				TB_PartidaFutbolito previousValue = this._TB_PartidaFutbolito.Entity;
				if (((previousValue != value) 
							|| (this._TB_PartidaFutbolito.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_PartidaFutbolito.Entity = null;
						previousValue.TB_Turno.Remove(this);
					}
					this._TB_PartidaFutbolito.Entity = value;
					if ((value != null))
					{
						value.TB_Turno.Add(this);
						this._identificadorPartida = value.identificadorJuego;
					}
					else
					{
						this._identificadorPartida = default(Nullable<long>);
					}
					this.SendPropertyChanged("TB_PartidaFutbolito");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_Usuario_TB_Turno", Storage="_TB_Usuario", ThisKey="usuarioGanador", OtherKey="identificadorUsuario", IsForeignKey=true)]
		public TB_Usuario TB_Usuario
		{
			get
			{
				return this._TB_Usuario.Entity;
			}
			set
			{
				TB_Usuario previousValue = this._TB_Usuario.Entity;
				if (((previousValue != value) 
							|| (this._TB_Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_Usuario.Entity = null;
						previousValue.TB_Turno.Remove(this);
					}
					this._TB_Usuario.Entity = value;
					if ((value != null))
					{
						value.TB_Turno.Add(this);
						this._usuarioGanador = value.identificadorUsuario;
					}
					else
					{
						this._usuarioGanador = default(Nullable<long>);
					}
					this.SendPropertyChanged("TB_Usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TB_Movimiento(TB_Movimiento entity)
		{
			this.SendPropertyChanging();
			entity.TB_Turno = this;
		}
		
		private void detach_TB_Movimiento(TB_Movimiento entity)
		{
			this.SendPropertyChanging();
			entity.TB_Turno = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_Usuario")]
	public partial class TB_Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _identificadorUsuario;
		
		private string _Nombre;
		
		private System.DateTime _FechaNacimiento;
		
		private string _Correo;
		
		private string _Contrasena;
		
		private int _Estatus;
		
		private System.Data.Linq.Binary _FotoPerfil;
		
		private EntitySet<TB_Amistad> _TB_Amistad;
		
		private EntitySet<TB_Amistad> _TB_Amistad1;
		
		private EntitySet<TB_Movimiento> _TB_Movimiento;
		
		private EntitySet<TB_PartidaFutbolito> _TB_PartidaFutbolito;
		
		private EntitySet<TB_PartidaFutbolito> _TB_PartidaFutbolito1;
		
		private EntitySet<TB_PartidaFutbolito> _TB_PartidaFutbolito2;
		
		private EntitySet<TB_PartidaGalaga> _TB_PartidaGalaga;
		
		private EntitySet<TB_Turno> _TB_Turno;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidentificadorUsuarioChanging(long value);
    partial void OnidentificadorUsuarioChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnFechaNacimientoChanging(System.DateTime value);
    partial void OnFechaNacimientoChanged();
    partial void OnCorreoChanging(string value);
    partial void OnCorreoChanged();
    partial void OnContrasenaChanging(string value);
    partial void OnContrasenaChanged();
    partial void OnEstatusChanging(int value);
    partial void OnEstatusChanged();
    partial void OnFotoPerfilChanging(System.Data.Linq.Binary value);
    partial void OnFotoPerfilChanged();
    #endregion
		
		public TB_Usuario()
		{
			this._TB_Amistad = new EntitySet<TB_Amistad>(new Action<TB_Amistad>(this.attach_TB_Amistad), new Action<TB_Amistad>(this.detach_TB_Amistad));
			this._TB_Amistad1 = new EntitySet<TB_Amistad>(new Action<TB_Amistad>(this.attach_TB_Amistad1), new Action<TB_Amistad>(this.detach_TB_Amistad1));
			this._TB_Movimiento = new EntitySet<TB_Movimiento>(new Action<TB_Movimiento>(this.attach_TB_Movimiento), new Action<TB_Movimiento>(this.detach_TB_Movimiento));
			this._TB_PartidaFutbolito = new EntitySet<TB_PartidaFutbolito>(new Action<TB_PartidaFutbolito>(this.attach_TB_PartidaFutbolito), new Action<TB_PartidaFutbolito>(this.detach_TB_PartidaFutbolito));
			this._TB_PartidaFutbolito1 = new EntitySet<TB_PartidaFutbolito>(new Action<TB_PartidaFutbolito>(this.attach_TB_PartidaFutbolito1), new Action<TB_PartidaFutbolito>(this.detach_TB_PartidaFutbolito1));
			this._TB_PartidaFutbolito2 = new EntitySet<TB_PartidaFutbolito>(new Action<TB_PartidaFutbolito>(this.attach_TB_PartidaFutbolito2), new Action<TB_PartidaFutbolito>(this.detach_TB_PartidaFutbolito2));
			this._TB_PartidaGalaga = new EntitySet<TB_PartidaGalaga>(new Action<TB_PartidaGalaga>(this.attach_TB_PartidaGalaga), new Action<TB_PartidaGalaga>(this.detach_TB_PartidaGalaga));
			this._TB_Turno = new EntitySet<TB_Turno>(new Action<TB_Turno>(this.attach_TB_Turno), new Action<TB_Turno>(this.detach_TB_Turno));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_identificadorUsuario", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long identificadorUsuario
		{
			get
			{
				return this._identificadorUsuario;
			}
			set
			{
				if ((this._identificadorUsuario != value))
				{
					this.OnidentificadorUsuarioChanging(value);
					this.SendPropertyChanging();
					this._identificadorUsuario = value;
					this.SendPropertyChanged("identificadorUsuario");
					this.OnidentificadorUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaNacimiento", DbType="DateTime NOT NULL")]
		public System.DateTime FechaNacimiento
		{
			get
			{
				return this._FechaNacimiento;
			}
			set
			{
				if ((this._FechaNacimiento != value))
				{
					this.OnFechaNacimientoChanging(value);
					this.SendPropertyChanging();
					this._FechaNacimiento = value;
					this.SendPropertyChanged("FechaNacimiento");
					this.OnFechaNacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Correo
		{
			get
			{
				return this._Correo;
			}
			set
			{
				if ((this._Correo != value))
				{
					this.OnCorreoChanging(value);
					this.SendPropertyChanging();
					this._Correo = value;
					this.SendPropertyChanged("Correo");
					this.OnCorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contrasena", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Contrasena
		{
			get
			{
				return this._Contrasena;
			}
			set
			{
				if ((this._Contrasena != value))
				{
					this.OnContrasenaChanging(value);
					this.SendPropertyChanging();
					this._Contrasena = value;
					this.SendPropertyChanged("Contrasena");
					this.OnContrasenaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estatus", DbType="Int NOT NULL")]
		public int Estatus
		{
			get
			{
				return this._Estatus;
			}
			set
			{
				if ((this._Estatus != value))
				{
					this.OnEstatusChanging(value);
					this.SendPropertyChanging();
					this._Estatus = value;
					this.SendPropertyChanged("Estatus");
					this.OnEstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FotoPerfil", DbType="VarBinary(MAX) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary FotoPerfil
		{
			get
			{
				return this._FotoPerfil;
			}
			set
			{
				if ((this._FotoPerfil != value))
				{
					this.OnFotoPerfilChanging(value);
					this.SendPropertyChanging();
					this._FotoPerfil = value;
					this.SendPropertyChanged("FotoPerfil");
					this.OnFotoPerfilChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_Usuario_TB_Amistad", Storage="_TB_Amistad", ThisKey="identificadorUsuario", OtherKey="identificadorUsuario1")]
		public EntitySet<TB_Amistad> TB_Amistad
		{
			get
			{
				return this._TB_Amistad;
			}
			set
			{
				this._TB_Amistad.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_Usuario_TB_Amistad1", Storage="_TB_Amistad1", ThisKey="identificadorUsuario", OtherKey="identificadorUsuario2")]
		public EntitySet<TB_Amistad> TB_Amistad1
		{
			get
			{
				return this._TB_Amistad1;
			}
			set
			{
				this._TB_Amistad1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_Usuario_TB_Movimiento", Storage="_TB_Movimiento", ThisKey="identificadorUsuario", OtherKey="identificadorUsuario")]
		public EntitySet<TB_Movimiento> TB_Movimiento
		{
			get
			{
				return this._TB_Movimiento;
			}
			set
			{
				this._TB_Movimiento.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_Usuario_TB_PartidaFutbolito", Storage="_TB_PartidaFutbolito", ThisKey="identificadorUsuario", OtherKey="identificadorUsuario1")]
		public EntitySet<TB_PartidaFutbolito> TB_PartidaFutbolito
		{
			get
			{
				return this._TB_PartidaFutbolito;
			}
			set
			{
				this._TB_PartidaFutbolito.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_Usuario_TB_PartidaFutbolito1", Storage="_TB_PartidaFutbolito1", ThisKey="identificadorUsuario", OtherKey="identificadorUsuario2")]
		public EntitySet<TB_PartidaFutbolito> TB_PartidaFutbolito1
		{
			get
			{
				return this._TB_PartidaFutbolito1;
			}
			set
			{
				this._TB_PartidaFutbolito1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_Usuario_TB_PartidaFutbolito2", Storage="_TB_PartidaFutbolito2", ThisKey="identificadorUsuario", OtherKey="usuarioGanadorPartida")]
		public EntitySet<TB_PartidaFutbolito> TB_PartidaFutbolito2
		{
			get
			{
				return this._TB_PartidaFutbolito2;
			}
			set
			{
				this._TB_PartidaFutbolito2.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_Usuario_TB_PartidaGalaga", Storage="_TB_PartidaGalaga", ThisKey="identificadorUsuario", OtherKey="identificadorUsuario1")]
		public EntitySet<TB_PartidaGalaga> TB_PartidaGalaga
		{
			get
			{
				return this._TB_PartidaGalaga;
			}
			set
			{
				this._TB_PartidaGalaga.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_Usuario_TB_Turno", Storage="_TB_Turno", ThisKey="identificadorUsuario", OtherKey="usuarioGanador")]
		public EntitySet<TB_Turno> TB_Turno
		{
			get
			{
				return this._TB_Turno;
			}
			set
			{
				this._TB_Turno.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TB_Amistad(TB_Amistad entity)
		{
			this.SendPropertyChanging();
			entity.TB_Usuario = this;
		}
		
		private void detach_TB_Amistad(TB_Amistad entity)
		{
			this.SendPropertyChanging();
			entity.TB_Usuario = null;
		}
		
		private void attach_TB_Amistad1(TB_Amistad entity)
		{
			this.SendPropertyChanging();
			entity.TB_Usuario1 = this;
		}
		
		private void detach_TB_Amistad1(TB_Amistad entity)
		{
			this.SendPropertyChanging();
			entity.TB_Usuario1 = null;
		}
		
		private void attach_TB_Movimiento(TB_Movimiento entity)
		{
			this.SendPropertyChanging();
			entity.TB_Usuario = this;
		}
		
		private void detach_TB_Movimiento(TB_Movimiento entity)
		{
			this.SendPropertyChanging();
			entity.TB_Usuario = null;
		}
		
		private void attach_TB_PartidaFutbolito(TB_PartidaFutbolito entity)
		{
			this.SendPropertyChanging();
			entity.TB_Usuario = this;
		}
		
		private void detach_TB_PartidaFutbolito(TB_PartidaFutbolito entity)
		{
			this.SendPropertyChanging();
			entity.TB_Usuario = null;
		}
		
		private void attach_TB_PartidaFutbolito1(TB_PartidaFutbolito entity)
		{
			this.SendPropertyChanging();
			entity.TB_Usuario1 = this;
		}
		
		private void detach_TB_PartidaFutbolito1(TB_PartidaFutbolito entity)
		{
			this.SendPropertyChanging();
			entity.TB_Usuario1 = null;
		}
		
		private void attach_TB_PartidaFutbolito2(TB_PartidaFutbolito entity)
		{
			this.SendPropertyChanging();
			entity.TB_Usuario2 = this;
		}
		
		private void detach_TB_PartidaFutbolito2(TB_PartidaFutbolito entity)
		{
			this.SendPropertyChanging();
			entity.TB_Usuario2 = null;
		}
		
		private void attach_TB_PartidaGalaga(TB_PartidaGalaga entity)
		{
			this.SendPropertyChanging();
			entity.TB_Usuario = this;
		}
		
		private void detach_TB_PartidaGalaga(TB_PartidaGalaga entity)
		{
			this.SendPropertyChanging();
			entity.TB_Usuario = null;
		}
		
		private void attach_TB_Turno(TB_Turno entity)
		{
			this.SendPropertyChanging();
			entity.TB_Usuario = this;
		}
		
		private void detach_TB_Turno(TB_Turno entity)
		{
			this.SendPropertyChanging();
			entity.TB_Usuario = null;
		}
	}
	
	public partial class SP_GalagaObtenerPuntuacionesUsuariosResult
	{
		
		private long _identificadorJuego;
		
		private long _identificadorUsuario1;
		
		private string _Nombre;
		
		private int _PuntajeUsuario1;
		
		private System.DateTime _fechaJuego;
		
		public SP_GalagaObtenerPuntuacionesUsuariosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_identificadorJuego", DbType="BigInt NOT NULL")]
		public long identificadorJuego
		{
			get
			{
				return this._identificadorJuego;
			}
			set
			{
				if ((this._identificadorJuego != value))
				{
					this._identificadorJuego = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_identificadorUsuario1", DbType="BigInt NOT NULL")]
		public long identificadorUsuario1
		{
			get
			{
				return this._identificadorUsuario1;
			}
			set
			{
				if ((this._identificadorUsuario1 != value))
				{
					this._identificadorUsuario1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PuntajeUsuario1", DbType="Int NOT NULL")]
		public int PuntajeUsuario1
		{
			get
			{
				return this._PuntajeUsuario1;
			}
			set
			{
				if ((this._PuntajeUsuario1 != value))
				{
					this._PuntajeUsuario1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaJuego", DbType="DateTime NOT NULL")]
		public System.DateTime fechaJuego
		{
			get
			{
				return this._fechaJuego;
			}
			set
			{
				if ((this._fechaJuego != value))
				{
					this._fechaJuego = value;
				}
			}
		}
	}
	
	public partial class SP_UsuarioVerificarResult
	{
		
		private long _identificadorUsuario;
		
		private string _Nombre;
		
		private System.DateTime _FechaNacimiento;
		
		private string _Correo;
		
		private System.Data.Linq.Binary _FotoPerfil;
		
		public SP_UsuarioVerificarResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_identificadorUsuario", DbType="BigInt NOT NULL")]
		public long identificadorUsuario
		{
			get
			{
				return this._identificadorUsuario;
			}
			set
			{
				if ((this._identificadorUsuario != value))
				{
					this._identificadorUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaNacimiento", DbType="DateTime NOT NULL")]
		public System.DateTime FechaNacimiento
		{
			get
			{
				return this._FechaNacimiento;
			}
			set
			{
				if ((this._FechaNacimiento != value))
				{
					this._FechaNacimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Correo
		{
			get
			{
				return this._Correo;
			}
			set
			{
				if ((this._Correo != value))
				{
					this._Correo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FotoPerfil", DbType="VarBinary(MAX) NOT NULL", CanBeNull=false)]
		public System.Data.Linq.Binary FotoPerfil
		{
			get
			{
				return this._FotoPerfil;
			}
			set
			{
				if ((this._FotoPerfil != value))
				{
					this._FotoPerfil = value;
				}
			}
		}
	}
	
	public partial class SP_UsuarioAmistadListarResult
	{
		
		private long _identificadorUsuario1;
		
		private string _NombreUsuario1;
		
		private long _identificadorUsuario2;
		
		private string _NombreUsuario2;
		
		private System.DateTime _FechaInicio;
		
		public SP_UsuarioAmistadListarResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_identificadorUsuario1", DbType="BigInt NOT NULL")]
		public long identificadorUsuario1
		{
			get
			{
				return this._identificadorUsuario1;
			}
			set
			{
				if ((this._identificadorUsuario1 != value))
				{
					this._identificadorUsuario1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreUsuario1", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string NombreUsuario1
		{
			get
			{
				return this._NombreUsuario1;
			}
			set
			{
				if ((this._NombreUsuario1 != value))
				{
					this._NombreUsuario1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_identificadorUsuario2", DbType="BigInt NOT NULL")]
		public long identificadorUsuario2
		{
			get
			{
				return this._identificadorUsuario2;
			}
			set
			{
				if ((this._identificadorUsuario2 != value))
				{
					this._identificadorUsuario2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreUsuario2", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string NombreUsuario2
		{
			get
			{
				return this._NombreUsuario2;
			}
			set
			{
				if ((this._NombreUsuario2 != value))
				{
					this._NombreUsuario2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaInicio", DbType="DateTime NOT NULL")]
		public System.DateTime FechaInicio
		{
			get
			{
				return this._FechaInicio;
			}
			set
			{
				if ((this._FechaInicio != value))
				{
					this._FechaInicio = value;
				}
			}
		}
	}
	
	public partial class SP_GalagaPuntuacionUsuarioResult
	{
		
		private long _identificadorJuego;
		
		private long _identificadorUsuario1;
		
		private int _PuntajeUsuario1;
		
		private double _duracion;
		
		private System.DateTime _fechaJuego;
		
		public SP_GalagaPuntuacionUsuarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_identificadorJuego", DbType="BigInt NOT NULL")]
		public long identificadorJuego
		{
			get
			{
				return this._identificadorJuego;
			}
			set
			{
				if ((this._identificadorJuego != value))
				{
					this._identificadorJuego = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_identificadorUsuario1", DbType="BigInt NOT NULL")]
		public long identificadorUsuario1
		{
			get
			{
				return this._identificadorUsuario1;
			}
			set
			{
				if ((this._identificadorUsuario1 != value))
				{
					this._identificadorUsuario1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PuntajeUsuario1", DbType="Int NOT NULL")]
		public int PuntajeUsuario1
		{
			get
			{
				return this._PuntajeUsuario1;
			}
			set
			{
				if ((this._PuntajeUsuario1 != value))
				{
					this._PuntajeUsuario1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_duracion", DbType="Float NOT NULL")]
		public double duracion
		{
			get
			{
				return this._duracion;
			}
			set
			{
				if ((this._duracion != value))
				{
					this._duracion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaJuego", DbType="DateTime NOT NULL")]
		public System.DateTime fechaJuego
		{
			get
			{
				return this._fechaJuego;
			}
			set
			{
				if ((this._fechaJuego != value))
				{
					this._fechaJuego = value;
				}
			}
		}
	}
	
	public partial class SP_FutbolitoBuscarPartidaResult
	{
		
		private System.Nullable<long> _identificadorUsuario1;
		
		private string _Nombre;
		
		public SP_FutbolitoBuscarPartidaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_identificadorUsuario1", DbType="BigInt")]
		public System.Nullable<long> identificadorUsuario1
		{
			get
			{
				return this._identificadorUsuario1;
			}
			set
			{
				if ((this._identificadorUsuario1 != value))
				{
					this._identificadorUsuario1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(255)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
	}
	
	public partial class SP_FutbolitoTraerDatosPartidaResult
	{
		
		private long _identificadorUsuario1;
		
		private System.Nullable<long> _identificadorUsuario2;
		
		private System.Nullable<long> _usuarioGanadorPartida;
		
		public SP_FutbolitoTraerDatosPartidaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_identificadorUsuario1", DbType="BigInt NOT NULL")]
		public long identificadorUsuario1
		{
			get
			{
				return this._identificadorUsuario1;
			}
			set
			{
				if ((this._identificadorUsuario1 != value))
				{
					this._identificadorUsuario1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_identificadorUsuario2", DbType="BigInt")]
		public System.Nullable<long> identificadorUsuario2
		{
			get
			{
				return this._identificadorUsuario2;
			}
			set
			{
				if ((this._identificadorUsuario2 != value))
				{
					this._identificadorUsuario2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuarioGanadorPartida", DbType="BigInt")]
		public System.Nullable<long> usuarioGanadorPartida
		{
			get
			{
				return this._usuarioGanadorPartida;
			}
			set
			{
				if ((this._usuarioGanadorPartida != value))
				{
					this._usuarioGanadorPartida = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
